### ISSUE TITLE
Feedback de segunda entrega de portafolio

### ISSUE THREAD

**Issue by adolivaresl** [AlejandraMoralesB/Personal-Web#1]
Hola Ale, estaba revisando esta segunda entrega de portafolio y realmente no hay feedback que darte, ya que no hay mayor info sobre tu prototipo o flujo de tu portafolio, tampoco hay algún deploy, asi que espero que en un corto plazo puedas trabajar en ello para asi poder ayudarte.

**Comment by AlejandraMoralesB** [comment]
Gracias por el feedback Domi , mejoraré en los aspectos señalados , según el deploy revisado hoy .
